apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
spec:
  template:
    spec:
      hostAliases:
        - ip: 145.89.192.138
          hostnames:
            - git.open-ict.hu
