apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-tls
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
spec:
  secretName: argo-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argo.git.open-ict.hu
