apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Upstream release; only the reboot window is patched locally.
resources:
  - https://github.com/kubereboot/kured/releases/download/1.15.0/kured-1.15.0-dockerhub.yaml

patches:
  - path: reboot-window-patch.yaml
