#!/usr/bin/env bash
# Manage the sealed-secrets keypair that every SealedSecret in git is
# encrypted for.
#
# The keypair lives on the deploy host as sealed-secrets-key.yaml (repo
# root, gitignored — same posture as terraform.tfvars) and is installed into
# kube-system by scripts/01-bootstrap-first-master.sh BEFORE Argo CD deploys
# the controller. The controller adopts it instead of generating its own, so
# a rebuilt cluster decrypts the SealedSecrets already in git. Without this,
# each new cluster gets a fresh random key and every committed SealedSecret
# is undecryptable.
#
# Usage:
#   scripts/sealing-key.sh ensure       generate the keypair if it is missing
#   scripts/sealing-key.sh verify       check every committed SealedSecret
#                                       decrypts with it (needs kubeseal)
#   scripts/sealing-key.sh cert <out>   write its public certificate to <out>
#   scripts/sealing-key.sh has-cert     exit 0 if the PEM cert on stdin is
#                                       one of its keys (used by scripts/06)
#
# The file is a kube-system Secret manifest; `kubectl get secret -n
# kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml`
# (a List, one entry per key) is accepted too. Override the path with
# SEALED_SECRETS_KEY.
#
# BACK IT UP off-host (password manager / vault). Losing it means resealing
# every secret; leaking it exposes every secret in git.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib-functions.sh
source "${SCRIPT_DIR}/lib-functions.sh"

MANIFESTS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
KEY_FILE="${SEALED_SECRETS_KEY:-${MANIFESTS_DIR}/sealed-secrets-key.yaml}"

# Print the base64 values of <field> (tls.crt / tls.key), one per key.
key_field() {
  sed -n "s/^[[:space:]]*${1//./\\.}:[[:space:]]*//p" "${KEY_FILE}"
}

require_key_file() {
  [[ -f "${KEY_FILE}" ]] || die "Sealing key not found: ${KEY_FILE} — run: bash scripts/sealing-key.sh ensure"
  [[ -n "$(key_field tls.key)" ]] || die "No tls.key entries in ${KEY_FILE}"
}

cmd_ensure() {
  if [[ -f "${KEY_FILE}" ]]; then
    log "Using sealing key: ${KEY_FILE}"
    return 0
  fi
  require_binary openssl
  local tmp
  tmp="$(mktemp -d)"
  # shellcheck disable=SC2064
  trap "rm -rf '${tmp}'" RETURN
  # Same shape as the controller's own generated key (RSA 4096, CN/O
  # sealed-secret); the active label is what makes the controller use it.
  openssl req -x509 -nodes -newkey rsa:4096 -days 3650 \
    -keyout "${tmp}/tls.key" -out "${tmp}/tls.crt" \
    -subj "/CN=sealed-secret/O=sealed-secret" 2>/dev/null \
    || die "openssl failed to generate the sealing key"
  (
    umask 077
    cat > "${KEY_FILE}" <<EOF
# Sealed-secrets keypair — PRIVATE KEY, never commit (gitignored).
# Generated by scripts/sealing-key.sh; installed by scripts/01.
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-key
  namespace: kube-system
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
data:
  tls.crt: $(base64 -w0 < "${tmp}/tls.crt")
  tls.key: $(base64 -w0 < "${tmp}/tls.key")
EOF
  )
  log "Generated sealing key: ${KEY_FILE}"
  warn "Back this file up off-host now — it is the only way to decrypt the SealedSecrets in git."
}

cmd_cert() {
  local out="${1:?usage: sealing-key.sh cert <out>}"
  require_key_file
  key_field tls.crt | head -n1 | base64 -d > "${out}"
}

# Exit 0 when the PEM certificate on stdin belongs to one of the keys.
cmd_has_cert() {
  require_key_file
  local want b64
  want="$(tr -d '\r\n')"
  while read -r b64; do
    [[ "$(echo "${b64}" | base64 -d | tr -d '\r\n')" == "${want}" ]] && return 0
  done < <(key_field tls.crt)
  return 1
}

cmd_verify() {
  require_key_file
  require_binary kubeseal
  local tmp keys="" i=0 b64 f failed=()
  tmp="$(mktemp -d)"
  # shellcheck disable=SC2064
  trap "rm -rf '${tmp}'" RETURN
  while read -r b64; do
    i=$((i + 1))
    echo "${b64}" | base64 -d > "${tmp}/key${i}.pem"
    keys+="${keys:+,}${tmp}/key${i}.pem"
  done < <(key_field tls.key)

  while IFS= read -r f; do
    # recovery-unseal happily "decrypts" an empty file.
    if ! grep -q '^kind: SealedSecret' "${f}"; then
      failed+=("${f#"${MANIFESTS_DIR}"/}: not a SealedSecret")
    elif ! kubeseal --recovery-unseal --recovery-private-key "${keys}" \
        < "${f}" > /dev/null 2> "${tmp}/err"; then
      failed+=("${f#"${MANIFESTS_DIR}"/}: $(head -n1 "${tmp}/err")")
    fi
  done < <(find "${MANIFESTS_DIR}/apps" -name 'sealedsecret-*.yaml' | sort)

  if [[ ${#failed[@]} -gt 0 ]]; then
    printf '  %s\n' "${failed[@]}" >&2
    die "These SealedSecrets do not decrypt with ${KEY_FILE}. Either put the
  key they were sealed with in that file (export it from the old cluster:
    kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > sealed-secrets-key.yaml)
  or reseal them for this key: delete the files above, run
  bash scripts/06-seal-secrets.sh (works without a cluster), commit + push."
  fi
  log "All committed SealedSecrets decrypt with ${KEY_FILE}"
}

case "${1:-}" in
  ensure) cmd_ensure ;;
  verify) cmd_verify ;;
  cert) shift; cmd_cert "$@" ;;
  has-cert) cmd_has_cert ;;
  *) die "usage: $0 ensure|verify|cert <out>|has-cert" ;;
esac
