apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-repos
  namespace: atlantis
  labels:
    app.kubernetes.io/name: atlantis
    app.kubernetes.io/part-of: gitops
data:
  repos.yaml: |
    repos:
      - id: /.*/
        workflow: default
        allowed_overrides: []
        allow_custom_workflows: false
