apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
  namespace: atlantis
  labels: &labels
    app.kubernetes.io/name: atlantis
    app.kubernetes.io/part-of: gitops

spec:
  serviceName: atlantis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atlantis

  template:
    metadata:
      labels: *labels

    spec:
      serviceAccountName: atlantis

      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      initContainers:
        - name: git-config
          image: ghcr.io/runatlantis/atlantis:v0.31.0
          command: ["/bin/sh", "-c"]
          envFrom:
            - secretRef:
                name: atlantis-vcs
          args:
            - |
              git config --file /gitconfig \
                url.http://gitea-http.gitea.svc.cluster.local:3000/.insteadOf \
                https://${username}:${token}@git.open-ict.hu/

              git config --file /gitconfig --add \
                url.http://gitea-http.gitea.svc.cluster.local:3000/.insteadOf \
                https://git.open-ict.hu/

              git config --file /gitconfig \
                credential.http://gitea-http.gitea.svc.cluster.local:3000.helper \
                '!f(){ echo username=$username; echo password=$token; }; f'

          volumeMounts:
            - name: gitconfig
              mountPath: /gitconfig
              subPath: gitconfig

      containers:
        - name: atlantis
          image: ghcr.io/runatlantis/atlantis:v0.31.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 4141

          env:
            - { name: ATLANTIS_DATA_DIR, value: /atlantis }
            - { name: ATLANTIS_PORT, value: "4141" }
            - { name: ATLANTIS_ATLANTIS_URL, value: "https://atlantis.git.open-ict.hu" }
            - { name: ATLANTIS_REPO_ALLOWLIST, value: "git.open-ict.hu/*" }
            - { name: ATLANTIS_GITEA_BASE_URL, value: "http://gitea-http.gitea.svc.cluster.local:3000" }
            - { name: ATLANTIS_REPO_CONFIG, value: /etc/atlantis/repos.yaml }
            - { name: GIT_CONFIG_GLOBAL, value: /gitconfig }

          envFrom:
            - secretRef:
                name: atlantis-vcs
            - secretRef:
                name: garage-s3-credentials

          livenessProbe: &probe
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60

          readinessProbe: *probe

          volumeMounts:
            - name: data
              mountPath: /atlantis

            - name: repos-config
              mountPath: /etc/atlantis/repos.yaml
              subPath: repos.yaml
              readOnly: true

            - name: gitconfig
              mountPath: /gitconfig
              subPath: gitconfig

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]

      volumes:
        - name: repos-config
          configMap:
            name: atlantis-repos

        - name: gitconfig
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi