apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-tls
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: source-control
spec:
  secretName: gitea-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - git.open-ict.hu
