---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-oidc-authentik
  namespace: gitea
spec:
  encryptedData:
    key: AgB3acK32hxsctJ7qx/LYf9GQt0DFTqLJk+VQPqp2x7cwkCEDVd9YWbJSwze03KHkkW+rrfIZaSz6DCUyQ3l1kQ18AkVXhZAM8tQ8LaKSqSqNA3YUSSrfj+LCP8iFyd9Y+tYZnLazWooPhWY6SU6bFNq5GAC582Yw5XlOJLAvhoT9Pn3RKUpPWCXreLi+5Il+kV5hmOLdl0w0L16899DsZIi3o3ek657wJFGAwJ6ZeSSPGm7tXdaSmi/7owWLITZnMK5S/8WXz/vDtFlzZ40fWu0b+zuacxlfbZgUDLjtUltn3w17ZWIqi1uhh0Ax97Jy4vxy5kt3OrP66gjBCrKUYNYsIEYfn9+rWEaXwI8LpKZTOKSqiL6W3K0Pv73F0agL94GYYIdYLSvYqACqYonHfuP2qA9QIOdVgY+9lK+jRNqD2bMlGK33cClnBlQyZxfItmlMhlxcWmabGbQPUZmiru29W8/Ok+48zdU7fDQeOk6KXtDPS98BTvV02yO+fLurzU0dGdI+bMl3VTRwIJcC2JV0jFPZlaNUS6dm5yBttZUIb7Of6GAxJVaqP7sndkRZWZMh8rP8MkXOUys2Iyl5KZN0Ace8VZ4LLm63DU37kfjqz92LTxlwLCH4wQApe3nVGjdFUNvpKFKUtcah3wdMGozmY45+/voVa8JeA6bbFpQKBT9U+VMjsPKqgwMFbpUc7PFuAicp45jVyR6ED56PLNwjd8kTRa3HPDCVvAjk7DjJ5UertteHgO/
    secret: AgBwgfEF/89IFFSXmtUkEXBDYJVfWj2/RYafR45NWBTR9LwE7ek13ckcNDvEs7INQUwjj0vemDdXoD7DLNSx7jtoQXjM6C0+cUg93aqqgLB0vDFfZHkUgvrJyg+hdsQjj8NqOp8QGPoSQu9rE1WTDz1zgFS92uAnlZCo+RFHLsRfGk9t5H2jdSbPWfuqXHBB47nP8qCx0fUBLIlAUrT3joDK5m+WmXcuVdzovNDDtiRdI/uLbBM0HihEcAEGjRD7iKRAQUbexW7kBBRdBWo90HmXwLvsEKoLkkKY4auu6AIu4ifs1DZRoTNZIXbYF2PpprwNeOVkL4U3ISO6DO5Mr0NhlIG3hphLGFXTvoVKuPTI3dpzQznXGuKsjigQrWshHLr4JLVkfCuBa0FevSMTSABKAvOZRy+dYvfFy/M1Vo3M7aEhe3u1CLK+CVzuELlNN4Ihgu59WFb3YP93L/K7EOV0RW4brnAyrB70RGqDLMpjJD3f3iw7mJlsCi255DQSAhuUGql5ICzQomk6GklpupxakxmVUsen7skyqaZHuccEKPpNYHeQQctPQn9jw21OVWKsXGg4xjWC+JOvE84glHrymxZQ2+ktMTL8CFTbOhmx3TsMKti8zwvTKpkBvPN0js8nOXOepm63VAzJgmbtMP+6YL9nt9JZ1os+XvpOuW7MAG1D4V7M7XXa6+miT0Hf27vYpEiLnXIti1W0WsgVkKAQR6ZYR7ssTMEOrArE5sgHaM7/+iLaNudpWAWBovHRA91qEvqaNEm7HEXycEyavWzZKSl+9OuI+TRBxHzvTPOeXUFHAtnDhfJWbkBBckHAinAQ0KAMO0XK7bz3uw4p4uGF3c49sRq3Zym3n/ueWXMaig==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-oidc-authentik
      namespace: gitea
