gitea:
  oauth:
    - name: Authentik
      provider: openidConnect
      existingSecret: gitea-oidc # Your secret is already bootstrapped
      autoDiscoverUrl: "https://auth.open-ict.hu/application/o/gitea/.well-known/openid-configuration"
      iconUrl: "https://auth.open-ict.hu/static/dist/assets/icons/icon.png"
      scopes: "email profile gitea"
      requiredClaimName: gitea
      groupClaimName: gitea
      adminGroup: admin
      restrictedGroup: restricted
